import { i18n } from '@/i18n-config';
import { RootLayoutProps } from '@/types';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Providers from '../../providers';
import './globals.css';

export const metadata: Metadata = {
  title: 'Hotel Quinto Nivel RD',
  description: 'Generated by create next app',
};

const poppinsSans = Poppins({
  variable: '--font-poppins-sans',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

/**
 * Root layout component for the application.
 *
 * This component serves as the main layout wrapper for all pages in the application.
 * It sets up the HTML structure with language support, applies global styles, and wraps
 * children with necessary providers.
 *
 * @param {Readonly<RootLayoutProps>} props - The component props
 * @param {React.ReactNode} props.children - The child components to be rendered within the layout
 * @param {Promise<{ lang: string }>} props.params - Route parameters containing language information
 *
 * @returns {Promise<JSX.Element>} The root layout structure with HTML and body elements
 *
 * @remarks
 * - Uses `suppressHydrationWarning` to prevent hydration warnings in development
 * - Applies Poppins font variable and utility classes for smooth scrolling and rendering
 * - Wraps children with Providers component for context and state management
 */

export default async function RootLayout({ children, params }: Readonly<RootLayoutProps>) {
  const { lang } = await params;
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppinsSans.variable} overscroll-contain scroll-smooth antialiased`}>
        <Providers lang={lang}>{children}</Providers>
      </body>
    </html>
  );
}
