import { i18n } from '@/i18n-config';
import { RootLayoutProps } from '@/types';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Providers from '../../providers';
import './globals.css';

export const metadata: Metadata = {
  title: 'Hotel Quinto Nivel RD',
  description: 'Generated by create next app',
};

const poppinsSans = Poppins({
  variable: '--font-poppins-sans',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({ children, params }: Readonly<RootLayoutProps>) {
  const { lang } = await params;
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppinsSans.variable} overscroll-contain scroll-smooth antialiased`}>
        <Providers lang={lang}>{children}</Providers>
      </body>
    </html>
  );
}
